# Generated by Django 2.2.1 on 2019-05-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moneris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ps_store_id', models.CharField(max_length=100)),
                ('hpp_key', models.CharField(max_length=100)),
                ('access_token', models.CharField(blank=True, max_length=100, null=True)),
                ('api_username', models.CharField(blank=True, max_length=100, null=True)),
                ('api_password', models.CharField(blank=True, max_length=100, null=True)),
                ('enviroment', models.CharField(choices=[('test', 'Test'), ('prod', 'Prod')], default='test', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
