# Generated by Django 2.2.1 on 2019-05-09 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneris', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moneris',
            old_name='enviroment',
            new_name='environment',
        ),
    ]
