# Generated by Django 2.2.1 on 2019-05-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='payment',
            field=models.CharField(choices=[('draft', 'Draft'), ('paid', 'Paid'), ('cancelled', 'Cancel')], default='draft', max_length=111),
        ),
    ]
