# Generated by Django 2.2.1 on 2019-05-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_auto_20190510_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='price',
            field=models.FloatField(default=22),
            preserve_default=False,
        ),
    ]
